/**
 * Generate TypeScript types from FastAPI OpenAPI JSON.
 * Usage: npm run gen:types  (requires API at ZM_API_OPENAPI or http://127.0.0.1:8000/openapi.json)
 * Offline fallback: copies a checked-in openapi snapshot if fetch fails.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outFile = path.join(__dirname, '../src/api/generated.ts');
const snapshot = path.join(__dirname, '../src/api/openapi.snapshot.json');
const url = process.env.ZM_API_OPENAPI || 'http://127.0.0.1:8000/openapi.json';

function schemaToTs(name, schema, schemas) {
  if (!schema) return 'unknown';
  if (schema.$ref) {
    const ref = schema.$ref.split('/').pop();
    return ref || 'unknown';
  }
  if (schema.enum) {
    return schema.enum.map((v) => JSON.stringify(v)).join(' | ');
  }
  if (schema.type === 'string') return 'string';
  if (schema.type === 'integer' || schema.type === 'number') return 'number';
  if (schema.type === 'boolean') return 'boolean';
  if (schema.type === 'array') return `Array<${schemaToTs(name, schema.items, schemas)}>`;
  if (schema.type === 'object' || schema.properties) {
    const props = schema.properties || {};
    const req = new Set(schema.required || []);
    const entries = Object.entries(props);
    if (entries.length === 0) return 'Record<string, unknown>';
    const lines = entries.map(([k, v]) => {
      const opt = req.has(k) ? '' : '?';
      return `  ${k}${opt}: ${schemaToTs(k, v, schemas)};`;
    });
    return `{\n${lines.join('\n')}\n}`;
  }
  return 'unknown';
}

async function loadOpenapi() {
  try {
    const res = await fetch(url);
    if (!res.ok) throw new Error(String(res.status));
    const json = await res.json();
    fs.writeFileSync(snapshot, `${JSON.stringify(json, null, 2)}\n`);
    return json;
  } catch {
    if (fs.existsSync(snapshot)) {
      console.warn('API unreachable — using openapi.snapshot.json');
      return JSON.parse(fs.readFileSync(snapshot, 'utf8'));
    }
    throw new Error(`Cannot load OpenAPI from ${url} and no snapshot present`);
  }
}

const openapi = await loadOpenapi();
const schemas = openapi.components?.schemas || {};
const parts = [
  '/** AUTO-GENERATED by npm run gen:types — do not edit by hand. */',
  '',
];
for (const [name, schema] of Object.entries(schemas)) {
  parts.push(`export type ${name} = ${schemaToTs(name, schema, schemas)};`, '');
}
fs.writeFileSync(outFile, `${parts.join('\n')}\n`);
console.log(`Wrote ${outFile} (${Object.keys(schemas).length} types)`);
