/** AUTO-GENERATED by npm run gen:types  -  do not edit by hand. */

export type ChatBody = {
  message: string;
  language?: string;
  decision?: unknown;
};

export type DemoLoginRequest = {
  role:
    | "CHW"
    | "HEALTH_CENTER"
    | "RBC_ADMIN"
    | "SUPER_ADMIN"
    | "chw"
    | "nurse"
    | "supervisor"
    | "rbc"
    | "SUPERVISOR"
    | "RBC_OFFICER";
};

export type ExplainBody = {
  decision: string;
  reasons?: Array<string>;
  triggered_rules?: Array<string>;
  language?: string;
};

export type ExtractBody = {
  free_text: string;
  language?: string;
  age_months?: unknown;
  sex?: unknown;
  temperature_c?: unknown;
  fever_days?: unknown;
  tdr_result?: unknown;
};

export type ExtractRequest = {
  text: string;
  language?: string;
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type HealthOut = {
  status: string;
  synthetic?: boolean;
  disclaimer: string;
  demo_today: string;
};

export type InsightsBody = {
  aggregated_stats: Record<string, unknown>;
  language?: string;
};

export type LoginRequest = {
  username: string;
  password: string;
};

export type ReferralCreate = {
  client_uuid: string;
  facility_id: string;
  chw_id?: string;
  district: string;
  sector?: string;
  age_months: number;
  sex?: string;
  decision: "refer" | "urgent_refer";
  reasons?: Array<string>;
  summary?: string;
  case_id?: unknown;
  convulsions?: boolean;
  unable_to_drink?: boolean;
  vomiting_everything?: boolean;
  lethargy?: boolean;
  severe_breathing_difficulty?: boolean;
  temperature_c?: unknown;
  fever_days?: unknown;
  tdr_result?: unknown;
};

export type ReferralMessageCreate = {
  body: string;
};

export type ReferralMessageOut = {
  id: string;
  referral_id: string;
  sender_id?: unknown;
  sender_role: string;
  body: string;
  created_at: string;
  read_at?: unknown;
};

export type ReferralOut = {
  id: string;
  client_uuid: string;
  facility_id: string;
  chw_id: string;
  district: string;
  sector: string;
  age_months: number;
  sex: string;
  decision: string;
  reasons: Array<string>;
  summary: string;
  status: string;
  created_at: string;
  received_at?: unknown;
  arrived_at?: unknown;
  treated_at?: unknown;
  demo_flag?: boolean;
  overdue?: boolean;
};

export type SpeakBody = {
  phrase_id: string;
  language?: string;
  text: string;
};

export type StatusUpdate = {
  status: "received" | "arrived" | "treated";
};

export type SyncItem = {
  client_uuid: string;
  type: "referral" | "triage";
  payload: Record<string, unknown>;
};

export type SyncRequest = {
  items: Array<SyncItem>;
};

export type SyncResponse = {
  accepted: number;
  duplicates: number;
  results: Array<Record<string, unknown>>;
};

export type TokenOut = {
  access_token: string;
  token_type?: string;
  user: UserOut;
};

export type TriageRequest = {
  age_months: number;
  sex?: "female" | "male";
  temperature_c: number;
  fever_days: number;
  convulsions?: boolean;
  unable_to_drink?: boolean;
  vomiting_everything?: boolean;
  lethargy?: boolean;
  severe_breathing_difficulty?: boolean;
  tdr_result?: "positive" | "negative" | "invalid";
  language?: string;
  use_ml?: boolean;
  free_text?: unknown;
};

export type TriageResponse = {
  decision: string;
  rules_decision: string;
  reasons: Array<string>;
  triggered_rules: Array<string>;
  ml_escalated: boolean;
  severe_risk?: unknown;
  referral_noncompletion_risk?: unknown;
  shap_factors?: Array<string>;
  confidence?: unknown;
  human_confirmation_required?: boolean;
  disclaimer: string;
  synthetic_note: string;
  extracted_from_text?: unknown;
};

export type UserCreate = {
  username: string;
  password: string;
  display_name: string;
  role?: string;
  phone?: string;
  district?: string;
  facility_id?: string;
  village?: string;
  chw_code?: string;
};

export type UserOut = {
  id: string;
  username: string;
  display_name: string;
  role: string;
  phone: string;
  district: string;
  facility_id: string;
  village: string;
  chw_code: string;
  active: boolean;
};

export type UserPatch = {
  active?: unknown;
  facility_id?: unknown;
  village?: unknown;
  district?: unknown;
  phone?: unknown;
  display_name?: unknown;
};

export type ValidationError = {
  loc: Array<unknown>;
  msg: string;
  type: string;
  input?: unknown;
  ctx?: Record<string, unknown>;
};

